- name: Adicionando repo do HELM
  command:
    helm repo add stable {{ url_repo_helm }}
  register: helm_add_repo

- name: Atualizando repo HELM
  command:
    helm repo update
  register: helm_repo_update

- name:  Instalando o Prometheus Operator
  shell: helm install {{ deploy_prometheus }}
  register: prometheus_install