

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles: 
  - { role: create-cluster, tags: ["create_cluster_role"] }

- hosts: k8s-workers
  become: yes
  user: ubuntu
  roles:
  - { role: join-workers, tags: ["join_workers_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles: 
  - { role: install-helm, tags: ["install_helm_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles: 
  - { role: install-monit-tools, tags: ["install_monit_tools_role"] }